# Uncomment the next line to define a global platform for your project

platform :ios, '15.0'

target 'Chandan_Controls' do

  #pod 'CAAutoFillTextField'
  pod 'CAAutoFillTextField', :path => '~/Documents/GitHub/CAAutoFillTextField'

end
